name: Trigger based on file change

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - '*recipe*.yml'
  #pull_request:
    #branches: [ "main" ]

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: file_change
        with:
          filters: |
            src:
              - '30x-main-recipe.yml'
      
      - if: steps.file_change.outputs.src == 'true'
        run: |
          echo "Triggering Firmware Repack Workflow"
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" https://api.github.com/repos/megharavi-globallogic/firmware-repack/actions/workflows/45240923/dispatches -d '{"ref":"firmware_signing"}'
        shell: bash
